exe yaml file updated

diff --git a/.github/workflows/build-windows-executable-app.yaml b/.github/workflows/build-windows-executable-app.yaml
--- a/.github/workflows/build-windows-executable-app.yaml
+++ b/.github/workflows/build-windows-executable-app.yaml
@@ -28,18 +28,11 @@ jobs:
         python -m pip install --upgrade pip
         pip install numpy  # Install numpy first
 
-    # Install Graphviz
-    - name: Install Graphviz dependencies
-      run: |
-        choco install graphviz --pre -y  # Installs Graphviz on Windows
-        # Confirm the Graphviz installation
-        # Verify installation of Graphviz using PowerShell's Start-Process
-        Start-Process -NoNewWindow -FilePath "C:\Program Files\Graphviz\bin\dot.exe" -ArgumentList "-V"
-
-
     - name: Install Required Packages
       run: |
-        python -m pip install -r requirements.txt
+        python -m pip install -r requirements.txt || true  # First attempt
+        # Attempt to install pygraphviz with Graphviz paths if the first attempt fails
+        python -m pip install pygraphviz --global-option=build_ext --global-option="-IC:\Program Files\Graphviz\include" --global-option="-LC:\Program Files\Graphviz\lib"
 
     - name: Create ChemProp2.bat file
       run: |
